spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI4G8iujyBCVw1zz6fjvJf
      secret-key: fiPmwheY0ziCC7QHOFcdbk0BSU0I99
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-mario
  application:
    name: gulimall-third-party



server:
  port: 30000
